name: core_framework
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

resolution: workspace

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  go_router: any
  path: any
  path_provider: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint_rules:
    path: ../lint_rules
